project:
  title: "How effective are individual-level interventions to help people detect misinformation?"
  type: website
  output-dir: docs
  
execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "Home"
  
  navbar:
    left:
      - file: data/data.qmd
      - file: literature_search/literature_search.qmd
    right:
      - icon: github
        aria-label: github
        href: https://github.com/andrewheiss/lemon-lucifer
        
  sidebar:
    - title: "Data"
      style: "docked"
      #search: false
      contents:
        - data/data.qmd
        - data/list_studies.qmd
    - title: "Literature Search"
      style: "docked"
      #search: false
      contents:
        - literature_search/literature_search.qmd
        - literature_search/identify_studies.qmd


  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} 2025 by Jan Pfänder<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/andrewheiss/lemon-lucifer)


format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: true
    code-tools: true
    css: styles.css
    toc: true



