---
title: "Codebook"
title-block-banner: true
execute:
  message: false
  warning: false
---

```{r}
#| echo: false

library(tidyverse)
library(kableExtra)  # for tables
library(readr)
```

```{r}
# make codebook
codebook <- data.frame(
  Variable_Name = c(
    "paper_id", 
    "experiment_id", 
    "subject_id", 
    "news_id", 
    "country", 
    "year", 
    "veracity", 
    "condition", 
    "intervention_label", 
    "intervention_description", 
    "intervention_selection",
    "intervention_selection_description",
    "control_label",
    "control_format", 
    "control_selection",
    "control_selection_description",
    "accuracy_raw", 
    "scale", 
    "originally_identified_treatment_effect", 
    "concordance", 
    "partisan_identity", 
    "news_slant", 
    "age", 
    "age_range", 
    "identified_via", 
    "id", 
    "unique_experiment_id", 
    "accuracy", 
    "recycled_news", 
    "recycled_news_reference", 
    "news_selection", 
    "long_term", 
    "time_elapsed"
  ),
  Values = c(
    "<code>character</code>", 
    "<code>integer</code>", 
    "<code>integer</code>", 
    "<code>integer</code>", 
    "<code>character</code>", 
    "<code>integer</code>", 
    "<code>true</code>, <code>false</code>", 
    "<code>treatment</code>, <code>control</code>", 
    "<code>character</code>", 
    "<code>character</code>", 
    "<code>character</code>", 
    "<code>character</code>", 
    "<code>character</code>", 
    "<code>picture</code>, <code>lede</code>, <code>source</code> (multiple possible), <code>facebook</code>", 
    "<code>character</code>", 
    "<code>character</code>", 
    "<code>integer</code>", 
    "<code>character</code>", 
    "<code>TRUE</code>, <code>FALSE</code>", 
    "<code>concordant</code>, <code>discordant</code>", 
    "<code>democrat</code>, <code>republican</code>", 
    "<code>democrat</code>, <code>republican</code>", 
    "<code>integer</code>", 
    "<code>character</code>", 
    "<code>character</code>", 
    "<code>character</code>",
    "<code>character</code>", 
    "<code>0</code>, <code>1</code>", 
    "<code>FALSE</code>, <code>TRUE</code>", 
    "<code>character</code>", 
    "<code>character</code>",
    "<code>TRUE</code>, <code>NA</code>", 
    "<code>integer</code>"
  ),
  Description = c(
    "Identifier for each paper",
    "Identifier for each experiment within a paper; start counting from 1; even if a paper has only one experiment, assign it an identifier",
    "Identifier of individual participants within an experiment",
    
    "Identifier of news headlines within an experiment",
    "The country of the sample",
    "Ideally year of data collection, otherwise year of publication",
    "Identifying false and true news items",
    "Treatment vs. control",
    "A label for what the intervention consisted of",
    "A detailed description of the intervention",
    "Only use if there is a choice to be made about how to treat different interventions: Pick the intervention_label that corresponds to the condition to keep, or a vector of intervention labels in cases there should be a merge", 
    "If multiple interventions tested within a single experiment (and related to a single control group), reasoning as to which intervention to select",
    "A label for what the control group consisted of. Only use if there are multiple control conditions and a choice needs to be made about which to pick", 
    "Which format the news were in, in the control condition. This is typically also the format of the treatement condition, but since sometimes the format varies (.e.g. when presence of source is manipulated), we code it as 'control' format. We take for granted that all studies show news headlines. Can take multiple values, either acombination of `picture`, `lede`, and `source`, or some social media format, e.g. 'facebook'.", 
    "Only use if there is a choice to be made about how to treat different control conditions: Sometimes when there are multiple interventions, there are also multiple control groups; indicate the control group (or groups, in case of a merge) to keep",
    "A detailed description of the chosen control group and why it has been chosen", 
    "Participants' accuracy ratings on the scale used in the original study (either a number, if Likert-type scale, or binary",
    "The scale used in the original study",
    "Whether the authors identified a significant treatment effect (`FALSE` if no, `TRUE` if yes)",
    "Political concordance of news items (concordant or discordant)",
    "Which party participants identify with (either Republican or Democrat). By contrast to concordance, we only code this variable for studies on US participants",
    "The political slant--if any--the news headline had. Limited to either Republican or Democrat, and only coded for studies on US participants",
    "Participant age. In some cases, participant age will not be exact, but within a binned category. In this case, we will take the mid-point of this category for the age variable",
    "Binned age, if only this is provided by the study.",
    "Indicates if a paper was identified by the systematic review or added after",
    "Unique participant ID (merged `paper_id`, `experiment_id`, `subject_id`)",
    "Unique experiment ID (merged `paper_id` and `experiment_id`)",
    "Binary version of `accuracy_raw`; unchanged if originally binary", 
    "Whether the set of news items has been taken from another paper", 
    "If from another paper, the reference of the paper the news items have been taken from",
    "Who selected the news items? (mostly 'researchers', but can also take other levels)", 
        "Some studies evaluate long-term effects of their intervention. We have a specific definition of what counts as a valid evaluation: The long-term effects need to be measured (i) on a new set of news headlines (ii) participants must not be exposed to the treatement again (we don't want to measure cumulative effects, but durability). Long-term evaluations are not included in our main analyses)", 
        "In case there are long-term effects, report the elapsed time (in days) between exposure to treatment and follow-up evaluation"
  ),
  stringsAsFactors = FALSE
)

write_csv(codebook, "codebook.csv")
```

You can download the combined individual-level data from all studies on the OSF project page soon. For a codebook, see @tbl-codebook, or download the codebook here [{{< fa file-csv >}} `codebook.csv`](codebook.csv). 

```{r}
#| label: tbl-codebook

# Generate the styled table with kableExtra
kable(codebook, 
      caption = "Codebook for variables to collect",
      col.names = c("Variable Name", "Values", "Description"),
      booktabs = TRUE,
      longtable = TRUE, 
      escape = FALSE, 
      format = "html") %>%
  kable_styling(latex_options = "repeat_header",
                font_size = 10) %>% 
  column_spec(1, bold = TRUE) %>%  # Bold the first column
  column_spec(2, width = "25em") %>%  # Set width for the description column
  row_spec(0, bold = TRUE)  # Bold the header row
```



