---
title: "Data"
title-block-banner: true
execute:
  message: false
  warning: false
---

```{r}
#| echo: false

library(tidyverse)
library(kableExtra)  # for tables
library(readr)
```

```{r}
# combine data

# List all matching files recursively
files <- list.files(
  path = "papers", 
  pattern = "^cleaned.*\\.rds$", 
  full.names = TRUE, 
  recursive = TRUE
)

# Load each file into a named list
studies_data <- lapply(files, function(file) {
  readRDS(file) |> 
    # ensure all identifier variables are of same variable type
    mutate(subject_id = as.character(subject_id), 
           scale = as.character(scale))
})

# Name list elements based on filenames (without extension or path)
names(studies_data) <- tools::file_path_sans_ext(basename(files))

data <- bind_rows(studies_data)

# build additional variables
write_csv(data, "data.csv")

```

```{r}
# make codebook
codebook <- data.frame(
  Variable_Name = c(
    "paper_id", "experiment_id", "subject_id", "news_id", "country", "year", 
    "veracity", "condition", "intervention_label", "intervention_description", 
    "intervention_selection",
    "intervention_selection_description",
    "control_selection",
    "accuracy_raw", "scale", "originally_identified_treatment_effect", 
    "concordance", "partisan_identity", "news_slant", "age", "age_range", "identified_via", "id", 
    "unique_experiment_id", "accuracy"
  ),
  Values = c(
    "<code>character</code>", "<code>integer</code>", "<code>integer</code>", "<code>integer</code>", "<code>character</code>", "<code>integer</code>", 
    "<code>true</code>, <code>false</code>", "<code>treatment</code>, <code>control</code>", "<code>character</code>", "<code>character</code>", 
    "<code>character</code>", 
    "<code>character</code>", 
    "<code>character</code>", 
    "<code>integer</code>", "<code>integer</code>", "<code>TRUE</code>, <code>FALSE</code>", "<code>concordant</code>, <code>discordant</code>", "<code>democrat</code>, <code>republican</code>", "<code>democrat</code>, <code>republican</code>", "<code>integer</code>", "<code>character</code>", "<code>character</code>", "<code>character</code>",
    "<code>character</code>", "<code>0</code>, <code>1</code>"
  ),
  Description = c(
    "Identifier for each paper",
    "Identifier for each experiment within a paper; start counting from 1; even if a paper has only one experiment, assign it an identifier",
    "Identifier of individual participants within an experiment",
    "Identifier of news headlines within an experiment",
    "The country of the sample",
    "Ideally year of data collection, otherwise year of publication",
    "Identifying false and true news items",
    "Treatment vs. control",
    "A label for what the intervention consisted of",
    "A detailed description of the intervention",
    "Only use if there is a choice to be made about how to treat different interventions: Pick the intervention_label that corresponds the the condition to keep, or a vector of intervention labels in cases there should be a merge", 
    "If multiple interventions tested within a single experiment (and related to a single control group), reasoning as to which intervention to select",
    "Only use if there is a choice to be made about how to treat different control conditions: Sometimes when there are multiple interventions, there are also multiple control groups; indicate the control group (or groups, in case of a merge) to keep",
    "Participants' accuracy ratings on the scale used in the original study",
    "The scale used in the original study",
    "Whether the authors identified a significant treatment effect (`FALSE` if no, `TRUE` if yes)",
    "Political concordance of news items (concordant or discordant)",
    "Which party participants identify with (either Republican or Democrat). By contrast to concordance, we only code this variable for studies on US participants",
    "The political slant--if any--the news headline had. Limited to either Republican or Democrat, and only coded for studies on US participants",
    "Participant age. In some cases, participant age will not be exact, but within a binned category. In this case, we will take the mid-point of this category for the age variable",
    "Binned age, if only this is provided by the study.",
    "Indicates if a paper was identified by the systematic review or added after",
    "Unique participant ID (merged `paper_id`, `experiment_id`, `subject_id`)",
    "Unique experiment ID (merged `paper_id` and `experiment_id`)",
    "Binary version of `accuracy_raw`; unchanged if originally binary"
  ),
  stringsAsFactors = FALSE
)

write_csv(codebook, "codebook.csv")
```

You can download the combined individual-level data from all studies here [{{< fa file-csv >}} `data.csv`](data.csv). For a codebook, see @tbl-codebook, or download the codebook here [{{< fa file-csv >}} `codebook.csv`](codebook.csv). 

```{r}
#| label: tbl-codebook

# Generate the styled table with kableExtra
kable(codebook, 
      caption = "Codebook for variables to collect",
      col.names = c("Variable Name", "Values", "Description"),
      booktabs = TRUE,
      longtable = TRUE, 
      escape = FALSE, 
      format = "html") %>%
  kable_styling(latex_options = "repeat_header",
                font_size = 10) %>% 
  column_spec(1, bold = TRUE) %>%  # Bold the first column
  column_spec(2, width = "25em") %>%  # Set width for the description column
  row_spec(0, bold = TRUE)  # Bold the header row
```



